server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: smart_proxy_logs
    static_configs:
    - targets:
        - localhost
      labels:
        job: smart_proxy
        service: phishing_detector
        environment: production
        __path__: /var/log/smart-proxy/*.json
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            message: message
            event: event
            confidence: confidence
            is_phishing: is_phishing
            domain: domain
            host: host
            url: url
            prediction_time: prediction_time
            analysis_time_ms: analysis_time_ms
            pattern_count: pattern_count
            keyword_count: keyword_count
            metric_name: metric_name
            client_id: client_id
            detection_method: detection_method
            ml_model_load_time: ml_model_load_time
            feature_count: feature_count
            detection_count: detection_count
            detection_types: detection_types
      - timestamp:
          source: timestamp
          format: unix_ms
      - labels:
          level:
          event:
          domain:
          is_phishing:
          detection_method:
