server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: ./positions.yaml

clients:
  - url: http://localhost:4100/loki/api/v1/push

scrape_configs:
  - job_name: smart_proxy
    static_configs:
    - targets:
        - localhost
      labels:
        job: smart_proxy
        __path__: C:/Users/igou/Desktop/bureau/smart proxy1/logs/*.json
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            message: message
            event: event
            confidence: confidence
            is_phishing: is_phishing
            domain: domain
            host: host
            url: url
            prediction_time: prediction_time
            analysis_time_ms: analysis_time_ms
            pattern_count: pattern_count
            keyword_count: keyword_count
            metric_name: metric_name
      - timestamp:
          source: timestamp
          format: unix_ms
